name: Deploy Shell App

on:
  workflow_dispatch:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Shell App
        run: |
          echo "🚀 Deploying shell-app..."
          cd shell-app
          vercel --prod --token=${{ secrets.VERCEL_TOKEN }} --yes
          echo "✅ shell-app deployed to production"
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}

      - name: Summary
        run: |
          echo "## ✅ Shell App Deployed" >> $GITHUB_STEP_SUMMARY
          echo "URL: https://shell-app-bice.vercel.app" >> $GITHUB_STEP_SUMMARY