name: Preview Deployment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Detect changes
        id: changes
        run: |
          CHANGED=$(npx turbo run build --filter='...[HEAD^1]' --dry=json | jq -r '.tasks[].package')
          echo "Changed packages: $CHANGED"
          echo "changed_apps=$CHANGED" >> $GITHUB_OUTPUT

      - name: Deploy Changed Apps to Preview
        run: |
          CHANGED="${{ steps.changes.outputs.changed_apps }}"

          for app in $CHANGED; do
            if [ "$app" != "vite-federation-workspace" ]; then
              echo "Deploying $app to preview..."
              cd $app
              vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
              vercel build --token=${{ secrets.VERCEL_TOKEN }}
              PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
              echo "- [$app]($PREVIEW_URL)" >> $GITHUB_STEP_SUMMARY
              cd ..
            fi
          done
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VITE_SHELL_REMOTE_ENTRY: ${{ secrets.VITE_SHELL_REMOTE_ENTRY }}
          VITE_DEMO_ONE_REMOTE_ENTRY: ${{ secrets.VITE_DEMO_ONE_REMOTE_ENTRY }}
          VITE_DEMO_TWO_REMOTE_ENTRY: ${{ secrets.VITE_DEMO_TWO_REMOTE_ENTRY }}
          VITE_DEMO_THREE_REMOTE_ENTRY: ${{ secrets.VITE_DEMO_THREE_REMOTE_ENTRY }}

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🚀 Preview deployment completed! Check the workflow summary for URLs.'
            })
